<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'App\\Daos\\PairItemCollectionDao' => $baseDir . '/app/Daos/PairItemCollectionDao.php',
    'App\\Daos\\PairItemDao' => $baseDir . '/app/Daos/PairItemDao.php',
    'App\\Daos\\PhoneNumItemCollectionDao' => $baseDir . '/app/Daos/PhoneNumItemCollectionDao.php',
    'App\\Daos\\PhoneNumItemDao' => $baseDir . '/app/Daos/PhoneNumItemDao.php',
    'App\\Managers\\AdminController' => $baseDir . '/app/Managers/userx/AdminController.php',
    'App\\Managers\\HomeController' => $baseDir . '/app/Managers/HomeController.php',
    'App\\Managers\\HomePageManager' => $baseDir . '/app/Managers/HomePageManager.php',
    'App\\Managers\\Manager' => $baseDir . '/app/Managers/Manager.php',
    'App\\Managers\\NameController' => $baseDir . '/app/Managers/NameController.php',
    'App\\Managers\\NewsController' => $baseDir . '/app/Managers/news/NewsController.php',
    'App\\Managers\\NickNameController' => $baseDir . '/app/Managers/NickNameController.php',
    'App\\Managers\\NickNameVipController' => $baseDir . '/app/Managers/NickNameVipController.php',
    'App\\Managers\\NotificationController' => $baseDir . '/app/Managers/NotificationController.php',
    'App\\Managers\\PersonController' => $baseDir . '/app/Managers/person/PersonController.php',
    'App\\Managers\\PersonManager' => $baseDir . '/app/Managers/person/PersonManager.php',
    'App\\Managers\\PhoneController' => $baseDir . '/app/Managers/PhoneController.php',
    'App\\Managers\\PlayStoreScraper' => $baseDir . '/app/Managers/PlayStoreScraper.php',
    'App\\Managers\\TabianController' => $baseDir . '/app/Managers/TabianController.php',
    'App\\Managers\\Telephone\\PairController' => $baseDir . '/app/Managers/Telephone/PairController.php',
    'App\\Managers\\Telephone\\PhoneNumberSellManager' => $baseDir . '/app/Managers/Telephone/PhoneNumberSellManager.php',
    'App\\Managers\\Telephone\\Util\\APIPhone' => $baseDir . '/app/Managers/Telephone/Util/APIPhone.php',
    'App\\Managers\\Telephone\\Util\\AppMessage' => $baseDir . '/app/Managers/Telephone/Util/AppMessage.php',
    'App\\Managers\\ThaiCalendarHelper' => $baseDir . '/app/Managers/ThaiCalendarHelper.php',
    'App\\Managers\\UserController' => $baseDir . '/app/Managers/userx/UserController.php',
    'App\\Middleware\\MemberMiddleware' => $baseDir . '/app/middlewares/MemberMiddleware.php',
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
);
