<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">

    <!-- Standard Meta -->
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <!-- Site Properties -->
    <title>ananya.in.th</title>

    <link rel="stylesheet" type="text/css" href="<?=PATH?>/views/semantic/semantic.min.css">
    <script src="<?=PATH?>views/semantic/semantic.min.js"></script>



</head>
<body>

<h3 class="ui orange top attached header"></h3>

<div class="ui attached segment">

</div>

</body>
</html>