#!/bin/bash

# วิธีแก้ปัญหา Gradle Permission
echo "🔧 แก้ปัญหา Gradle Permission"
echo ""
echo "ปัญหา: ไฟล์ .lck ถูก protect โดย macOS"
echo ""
echo "วิธีแก้ (เลือก 1 วิธี):"
echo ""
echo "1️⃣ ใช้ Android Studio (แนะนำที่สุด):"
echo "   - เปิด Android Studio"
echo "   - File > Open > เลือก /Users/tayap/project-number/number-android"
echo "   - Build > Rebuild Project"
echo "   - Run (Shift+F10)"
echo ""
echo "2️⃣ ลบไฟล์ผ่าน Finder:"
echo "   - กด Cmd+Shift+G"
echo "   - พิมพ์: ~/.gradle/wrapper/dists/gradle-9.1.0-bin/"
echo "   - ลบ folder '9agqghryom9wkf8r80qlhnts3' ทั้งหมด"
echo "   - แล้วรัน: ./run_all.sh"
echo ""
echo "3️⃣ ให้ Terminal Full Disk Access:"
echo "   - System Settings > Privacy & Security > Full Disk Access"
echo "   - เพิ่ม Terminal.app"
echo "   - Restart Terminal"
echo "   - แล้วรัน: rm -f ~/.gradle/wrapper/dists/gradle-9.1.0-bin/*/gradle-9.1.0-bin.zip.lck"
echo ""
echo "4️⃣ ใช้ Gradle ที่ติดตั้งแล้ว (ถ้ามี):"
echo "   - brew install gradle"
echo "   - gradle assembleRelease"
echo ""
