#!/bin/bash

# สคริปต์สำหรับ Build APK โดยใช้ Android Studio

echo "🔧 วิธีแก้ปัญหาการโหลดช้าที่ Home Tab"
echo "=========================================="
echo ""
echo "⚠️ ปัญหา: แอพที่รันอยู่ตอนนี้ยังเป็นโค้ดเก่าที่ยังไม่มี optimization"
echo ""
echo "✅ วิธีแก้:"
echo ""
echo "1️⃣ เปิด Android Studio"
echo "   - เปิดโปรเจกต์: /Users/tayap/project-number/number-android"
echo ""
echo "2️⃣ Build APK"
echo "   - กด Build → Build Bundle(s) / APK(s) → Build APK(s)"
echo "   - หรือกด: Shift + Cmd + F9"
echo ""
echo "3️⃣ ติดตั้งแอพใหม่"
echo "   - เชื่อมต่ออุปกรณ์หรือ emulator"
echo "   - กด Run → Run 'app'"
echo "   - หรือกด: Ctrl + R"
echo ""
echo "4️⃣ ทดสอบ"
echo "   - เปิดแอพและไปที่ HOME tab"
echo "   - สังเกตว่าโหลดเร็วขึ้นหรือไม่"
echo ""
echo "=========================================="
echo "📝 หมายเหตุ:"
echo "   - การแก้ไขโค้ดเสร็จสมบูรณ์แล้ว"
echo "   - แค่รอ build และติดตั้งเท่านั้น"
echo "   - คาดว่าจะเร็วขึ้น ~90%"
echo "=========================================="
